CREATE TABLE PARENT_TASK
(
ID INT(15) NOT NULL,
TASK VARCHAR(100)
);

ALTER TABLE PARENT_TASK ADD CONSTRAINT PARENT_TASK_PK PRIMARY KEY(ID);

CREATE TABLE TASK
(
ID INT(15) NOT NULL AUTO_INCREMENT,
PARENT_TASK_ID INT(15),
PROJECT_ID INT(15),
TASK VARCHAR(100),
START_DATE DATE,
END_DATE DATE,
PRIORITY INT(3),
STATUS VARCHAR(50),
PRIMARY KEY (ID)
);

CREATE TABLE PROJECT
(
ID INT(15) NOT NULL AUTO_INCREMENT,
PROJECT VARCHAR(100) NOT NULL,
START_DATE DATE,
END_DATE DATE,
PRIORITY INT(3),
PRIMARY KEY (ID)
);

CREATE TABLE USER
(
ID INT(15) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMPLOYEE_ID INT(15),
TASK_ID INT(15),
PROJECT_ID INT(15),
PRIMARY KEY (ID)
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);
ALTER TABLE USER ADD CONSTRAINT USER_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);
ALTER TABLE USER ADD CONSTRAINT USER_TASK_FK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID);