CREATE TABLE PARENT_TASK
(
ID NUMBER(15) NOT NULL,
TASK VARCHAR(100)
);

ALTER TABLE PARENT_TASK ADD CONSTRAINT PARENT_TASK_PK PRIMARY KEY(ID);

CREATE TABLE TASK
(
ID NUMBER(15) NOT NULL AUTO_INCREMENT,
PARENT_TASK_ID NUMBER(15),
PROJECT_ID NUMBER(15),
TASK VARCHAR(100),
START_DATE DATE,
END_DATE DATE,
PRIORITY NUMBER(3),
STATUS VARCHAR(50)
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PK PRIMARY KEY(ID);

CREATE TABLE PROJECT
(
ID NUMBER(15) NOT NULL AUTO_INCREMENT,
PROJECT VARCHAR(100) NOT NULL,
START_DATE DATE,
END_DATE DATE,
PRIORITY NUMBER(3)
);

ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_PK PRIMARY KEY(ID);

CREATE TABLE USER
(
ID NUMBER(15) NOT NULL AUTO_INCREMENT,
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
EMPLOYEE_ID NUMBER(15),
TASK_ID NUMBER(15),
PROJECT_ID NUMBER(15)
);

ALTER TABLE USER ADD CONSTRAINT USER_PK PRIMARY KEY(ID);

ALTER TABLE TASK ADD CONSTRAINT TASK_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);
ALTER TABLE USER ADD CONSTRAINT USER_PROJECT_FK FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(ID);
ALTER TABLE USER ADD CONSTRAINT USER_TASK_FK FOREIGN KEY (TASK_ID) REFERENCES TASK(ID);